server:
  tomcat:
    threads:
      max: 200
spring:
  datasource:
    username: root
    password: root
    url:  jdbc:mysql://192.168.1.100:3306/seckill?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 192.168.1.100
    database: 10

  rabbitmq:
    host: 192.168.1.100
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 10
        max-interval: 10000ms
        multiplier: 2

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
